[surface]
primary = "#090909"
secondary = "#121212"
tertiary = "#1A1A1A"
modal = "#222222"
accent = "#482FB8"
transparent = "#00000000"
demote = "#0D0D0D"
overlay = "#482FB808"

[state]
hover = "#ffffff02"
active = "#ffffff07"
selected = "#ffffff02"
disabled = "#ff0000"

[text]
default = "#CCCCCC"
muted = "#ffffff30"
disabled = "#2c2c2c"
placeholder = "#343434"
discreet = "#ffffff08"

[text.syntax]
default = "#D5D5D5"
comment = "#454545"
comment_doc = "#446850"
red = "#FF8787"
orange = "#F0A875"
yellow = "#F5DE89"
green = "#7DE898"
cyan = "#79E0EC"
blue = "#5D8DEE"
purple = "#8B76EA"
pink = "#F997E8"


[guide]
default = "#191919"
active = "#303030"


[git]
added = "#7DE898"
modified = "#F5DE89"
deleted = "#FF8787"
